[terminal]
shell = "zsh"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true

[font]
size = 14
builtin_box_drawing = false

[colors.bright]
red = "#bf616a"
blue = "#81a1c1"
cyan = "#8fbcbb"
black = "#4c566a"
green = "#a3be8c"
white = "#eceff4"
yellow = "#ebcb8b"
magenta = "#b48ead"

[colors.dim]
red = "#94545d"
blue = "#68809a"
cyan = "#6d96a5"
black = "#373e4d"
green = "#809575"
white = "#aeb3bb"
yellow = "#b29e75"
magenta = "#8c738c"

[colors.normal]
red = "#bf616a"
blue = "#81a1c1"
cyan = "#88c0d0"
black = "#3b4252"
green = "#a3be8c"
white = "#e5e9f0"
yellow = "#ebcb8b"
magenta = "#b48ead"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"
