[options]
Color
ILoveCandy
CheckSpace
CacheDir = /tmp
Architecture = auto
DownloadUser = alpm
ParallelDownloads = 5
HoldPkg = pacman glibc
LocalFileSigLevel = Optional
SigLevel = Required DatabaseOptional

[core]
Server = https://fastly.mirror.pkgbuild.com/$repo/os/$arch

[extra]
Server = https://fastly.mirror.pkgbuild.com/$repo/os/$arch
