#!/bin/sh

bspc monitor -d {1..9}
bspc config window_gap 1
bspc config border_width 1
bspc config focus_follows_pointer true
bspc config normal_border_color "#21222c"
bspc config focused_border_color "#bd93f9"

setxkbmap -layout br &
pidof -q sxhkd || sxhkd &
pidof -q polybar || polybar -r &
xsetroot -cursor_name left_ptr &
xrdb "$HOME"/.config/x11/xdefaults &
redshift -PO 5500 > /dev/null 2>&1 &
feh --bg-scale --no-fehbg "$HOME"/.local/share/wallpaper/first-collection/arch.png &
