#!/bin/zsh

bspc monitor -d {0..9}
bspc config window_gap 5
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#81a1c1"

echo "Xft.dpi: 96
Xft.rgba: rgb
Xft.hintstyle: hintslight" | xrdb &

pidof -q sxhkd || sxhkd &
xsetroot -cursor_name left_ptr &
pidof -q polybar || polybar -r &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --no-fehbg --bg-scale /usr/share/backgrounds/archlinux/small.png &
