#!/bin/bash

bspc monitor -d {0..9}
bspc config window_gap 5
bspc config normal_border_color '#2e3440'
bspc config focused_border_color '#81a1c1'

xset s off -dpms &
redshift -PO 6000K &
pidof -q sxhkd || sxhkd &
echo 'Xft.dpi: 96' | xrdb &
xsetroot -cursor_name left_ptr &
pidof -q polybar || polybar -r &
setxkbmap -layout br -model abnt2 &
xinput set-prop 9 'libinput Accel Profile Enabled' 0 1 0 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --no-fehbg --bg-scale /usr/share/backgrounds/archlinux/small.png &
