#!/usr/bin/env bash

for INDEX in {1..9}
do
    TAGS=$((1 << (INDEX - 1)))
    riverctl map normal Mod4 "$INDEX" set-focused-tags "$TAGS"
    riverctl map normal Mod4+Shift "$INDEX" set-view-tags "$TAGS"
done

riverctl border-width 1
riverctl keyboard-layout br
riverctl mouse pointer-accel flat
riverctl default-layout rivertile
riverctl default-attach-mode below
riverctl focus-follows-cursor normal
riverctl xcursor-theme Vanilla-DMZ 16
riverctl border-color-focused 0xbd93f9
riverctl hide-cursor when-typing enabled
riverctl border-color-unfocused 0x21222c

riverctl map normal Mod4 c close
riverctl map normal Mod4+Shift q exit
riverctl map normal Mod4 Return spawn foot
riverctl map normal Mod4 right focus-view next
riverctl map normal Mod4+Shift right swap next
riverctl map normal Mod4 left focus-view previous
riverctl map normal Mod4+Shift left swap previous
riverctl map normal Mod4+Shift f toggle-fullscreen

riverctl spawn 'rivertile -view-padding 1 -outer-padding 1 -main-ratio 0.5'
riverctl spawn 'swaybg -i ~/.local/share/wallpaper/first-collection/arch.png'
