export LESS="-R"
export EDITOR="nvim"
export BAT_THEME="Nord"
export LESSHISTFILE="-"
export MANPAGER="nvim +Man!"
export XDG_CACHE_HOME="/tmp"
export SUDO_PROMPT="Password:"
export NVIM_LOG_FILE="/dev/null"
export PS1="%B%F{blue}%1~%b%f $ "
export ZLE_REMOVE_SUFFIX_CHARS=""
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XAUTHORITY="$XDG_DATA_HOME/xorg/Xauthority"
export FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0"
