export EDITOR="nvim"
export WINEARCH="win32"
export BAT_THEME="Nord"
export MANPAGER="nvim +Man!"
export XDG_CACHE_HOME="/tmp"
export XDG_STATE_HOME="/tmp"
export SUDO_PROMPT="Password:"
export PS1="%B%F{blue}%1~%b%f $ "
export ZLE_REMOVE_SUFFIX_CHARS=""
export XAUTHORITY="/tmp/Xauthority"
export XDG_CONFIG_HOME="$HOME/.config"
export WINEPREFIX="$XDG_DATA_HOME/wine"
export XDG_DATA_HOME="$HOME/.local/share"
export FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0"
