unset HISTFILE
PS1='\[\e[1;34m\]\W\[\e[m\] $ '
source "$HOME/.config/shell/env.sh"
source "$HOME/.config/shell/alias.sh"

if test -d "$HOME/.local/share/dircolors"
then
    eval "$(dircolors "$HOME/.local/share/dircolors/src/dir_colors")"
fi
